[package]
name = "flom-config"
version = "0.1.0"
edition = "2024"

[dependencies]
flom-core = { path = "../flom-core" }
serde = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
thiserror = { workspace = true }
